name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: インストール
        run: bun install
      - name: ユニットテスト実行
        run: NODE_ENV=test bun test "src/**/*.test.ts"

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: インストール
        run: bun install
      - name: Playwrightインストール
        run: bunx playwright install chromium --with-deps
      - name: e2eテスト実行
        run: |
          # テスト環境変数を設定してPlaywrightを実行
          NODE_ENV=test PLAYWRIGHT_TEST=true bunx playwright test --project=chromium
